# .github/workflows/convert-to-pdf.yml

name: Convert markdown files to PDF
# This workflow is triggered on pushes to the repository.
on:
  push:
    # branches:
    #   - main
    paths:
      - 'MeTooinChina_*/**.md'

jobs:
  converttopdf:
    name: Build PDF
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: baileyjm02/markdown-to-pdf@v1
        with:
          input_dir: MeTooinChina_SimplifiedChinese
          output_dir: MeTooinChina_SimplifiedChinese
          build_html: false
